//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.Local.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account(s).
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit-Loss, History.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remittee.
        /// </summary>
        public static string Beneficiary {
            get {
                return ResourceManager.GetString("Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLang {
            get {
                return ResourceManager.GetString("ChangeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string DatumFrom {
            get {
                return ResourceManager.GetString("DatumFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string DatumTo {
            get {
                return ResourceManager.GetString("DatumTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp..
        /// </summary>
        public static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp. - Group.
        /// </summary>
        public static string Exp2 {
            get {
                return ResourceManager.GetString("Exp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expences.
        /// </summary>
        public static string Expences {
            get {
                return ResourceManager.GetString("Expences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expences - Date.
        /// </summary>
        public static string ExpencesOverDate {
            get {
                return ResourceManager.GetString("ExpencesOverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expences - Beneficiary.
        /// </summary>
        public static string ExpencesOverRemittee {
            get {
                return ResourceManager.GetString("ExpencesOverRemittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expences - Beneficiary Group.
        /// </summary>
        public static string ExpencesOverRemitteeGroups {
            get {
                return ResourceManager.GetString("ExpencesOverRemitteeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inc..
        /// </summary>
        public static string Inc {
            get {
                return ResourceManager.GetString("Inc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomes.
        /// </summary>
        public static string Incomes {
            get {
                return ResourceManager.GetString("Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomes - Date.
        /// </summary>
        public static string IncomesOverDate {
            get {
                return ResourceManager.GetString("IncomesOverDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Span.
        /// </summary>
        public static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update DataBank.
        /// </summary>
        public static string UpdateDataStorage {
            get {
                return ResourceManager.GetString("UpdateDataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Span.
        /// </summary>
        public static string UpdateDateSpan {
            get {
                return ResourceManager.GetString("UpdateDateSpan", resourceCulture);
            }
        }
    }
}
