//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceRefServARCode {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationRequest", Namespace="http://schemas.datacontract.org/2004/07/WcfServARR")]
    [System.SerializableAttribute()]
    public partial class AuthorizationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthRequestCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthRequestCode {
            get {
                return this.AuthRequestCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthRequestCodeField, value) != true)) {
                    this.AuthRequestCodeField = value;
                    this.RaisePropertyChanged("AuthRequestCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFirstName {
            get {
                return this.UserFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFirstNameField, value) != true)) {
                    this.UserFirstNameField = value;
                    this.RaisePropertyChanged("UserFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizationRequestFault", Namespace="http://schemas.datacontract.org/2004/07/WcfServARR")]
    [System.SerializableAttribute()]
    public partial class AuthorizationRequestFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefServARCode.IServARCode")]
    public interface IServARCode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServARCode/TryToRegisterAuthRequest", ReplyAction="http://tempuri.org/IServARCode/TryToRegisterAuthRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceRefServARCode.AuthorizationRequestFault), Action="http://tempuri.org/IServARCode/TryToRegisterAuthRequestAuthorizationRequestFaultF" +
            "ault", Name="AuthorizationRequestFault", Namespace="http://schemas.datacontract.org/2004/07/WcfServARR")]
        int TryToRegisterAuthRequest(WpfApplication1.ServiceRefServARCode.AuthorizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServARCode/TryToRegisterAuthRequest", ReplyAction="http://tempuri.org/IServARCode/TryToRegisterAuthRequestResponse")]
        System.IAsyncResult BeginTryToRegisterAuthRequest(WpfApplication1.ServiceRefServARCode.AuthorizationRequest request, System.AsyncCallback callback, object asyncState);
        
        int EndTryToRegisterAuthRequest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServARCode/GetAuthCode", ReplyAction="http://tempuri.org/IServARCode/GetAuthCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WpfApplication1.ServiceRefServARCode.AuthorizationRequestFault), Action="http://tempuri.org/IServARCode/GetAuthCodeAuthorizationRequestFaultFault", Name="AuthorizationRequestFault", Namespace="http://schemas.datacontract.org/2004/07/WcfServARR")]
        string GetAuthCode(int accoundId, string authorizReqCode);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServARCode/GetAuthCode", ReplyAction="http://tempuri.org/IServARCode/GetAuthCodeResponse")]
        System.IAsyncResult BeginGetAuthCode(int accoundId, string authorizReqCode, System.AsyncCallback callback, object asyncState);
        
        string EndGetAuthCode(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServARCodeChannel : WpfApplication1.ServiceRefServARCode.IServARCode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TryToRegisterAuthRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TryToRegisterAuthRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAuthCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAuthCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServARCodeClient : System.ServiceModel.ClientBase<WpfApplication1.ServiceRefServARCode.IServARCode>, WpfApplication1.ServiceRefServARCode.IServARCode {
        
        private BeginOperationDelegate onBeginTryToRegisterAuthRequestDelegate;
        
        private EndOperationDelegate onEndTryToRegisterAuthRequestDelegate;
        
        private System.Threading.SendOrPostCallback onTryToRegisterAuthRequestCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAuthCodeDelegate;
        
        private EndOperationDelegate onEndGetAuthCodeDelegate;
        
        private System.Threading.SendOrPostCallback onGetAuthCodeCompletedDelegate;
        
        public ServARCodeClient() {
        }
        
        public ServARCodeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServARCodeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServARCodeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServARCodeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<TryToRegisterAuthRequestCompletedEventArgs> TryToRegisterAuthRequestCompleted;
        
        public event System.EventHandler<GetAuthCodeCompletedEventArgs> GetAuthCodeCompleted;
        
        public int TryToRegisterAuthRequest(WpfApplication1.ServiceRefServARCode.AuthorizationRequest request) {
            return base.Channel.TryToRegisterAuthRequest(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginTryToRegisterAuthRequest(WpfApplication1.ServiceRefServARCode.AuthorizationRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTryToRegisterAuthRequest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndTryToRegisterAuthRequest(System.IAsyncResult result) {
            return base.Channel.EndTryToRegisterAuthRequest(result);
        }
        
        private System.IAsyncResult OnBeginTryToRegisterAuthRequest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WpfApplication1.ServiceRefServARCode.AuthorizationRequest request = ((WpfApplication1.ServiceRefServARCode.AuthorizationRequest)(inValues[0]));
            return this.BeginTryToRegisterAuthRequest(request, callback, asyncState);
        }
        
        private object[] OnEndTryToRegisterAuthRequest(System.IAsyncResult result) {
            int retVal = this.EndTryToRegisterAuthRequest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTryToRegisterAuthRequestCompleted(object state) {
            if ((this.TryToRegisterAuthRequestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TryToRegisterAuthRequestCompleted(this, new TryToRegisterAuthRequestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TryToRegisterAuthRequestAsync(WpfApplication1.ServiceRefServARCode.AuthorizationRequest request) {
            this.TryToRegisterAuthRequestAsync(request, null);
        }
        
        public void TryToRegisterAuthRequestAsync(WpfApplication1.ServiceRefServARCode.AuthorizationRequest request, object userState) {
            if ((this.onBeginTryToRegisterAuthRequestDelegate == null)) {
                this.onBeginTryToRegisterAuthRequestDelegate = new BeginOperationDelegate(this.OnBeginTryToRegisterAuthRequest);
            }
            if ((this.onEndTryToRegisterAuthRequestDelegate == null)) {
                this.onEndTryToRegisterAuthRequestDelegate = new EndOperationDelegate(this.OnEndTryToRegisterAuthRequest);
            }
            if ((this.onTryToRegisterAuthRequestCompletedDelegate == null)) {
                this.onTryToRegisterAuthRequestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTryToRegisterAuthRequestCompleted);
            }
            base.InvokeAsync(this.onBeginTryToRegisterAuthRequestDelegate, new object[] {
                        request}, this.onEndTryToRegisterAuthRequestDelegate, this.onTryToRegisterAuthRequestCompletedDelegate, userState);
        }
        
        public string GetAuthCode(int accoundId, string authorizReqCode) {
            return base.Channel.GetAuthCode(accoundId, authorizReqCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAuthCode(int accoundId, string authorizReqCode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAuthCode(accoundId, authorizReqCode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndGetAuthCode(System.IAsyncResult result) {
            return base.Channel.EndGetAuthCode(result);
        }
        
        private System.IAsyncResult OnBeginGetAuthCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int accoundId = ((int)(inValues[0]));
            string authorizReqCode = ((string)(inValues[1]));
            return this.BeginGetAuthCode(accoundId, authorizReqCode, callback, asyncState);
        }
        
        private object[] OnEndGetAuthCode(System.IAsyncResult result) {
            string retVal = this.EndGetAuthCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAuthCodeCompleted(object state) {
            if ((this.GetAuthCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAuthCodeCompleted(this, new GetAuthCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAuthCodeAsync(int accoundId, string authorizReqCode) {
            this.GetAuthCodeAsync(accoundId, authorizReqCode, null);
        }
        
        public void GetAuthCodeAsync(int accoundId, string authorizReqCode, object userState) {
            if ((this.onBeginGetAuthCodeDelegate == null)) {
                this.onBeginGetAuthCodeDelegate = new BeginOperationDelegate(this.OnBeginGetAuthCode);
            }
            if ((this.onEndGetAuthCodeDelegate == null)) {
                this.onEndGetAuthCodeDelegate = new EndOperationDelegate(this.OnEndGetAuthCode);
            }
            if ((this.onGetAuthCodeCompletedDelegate == null)) {
                this.onGetAuthCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAuthCodeCompleted);
            }
            base.InvokeAsync(this.onBeginGetAuthCodeDelegate, new object[] {
                        accoundId,
                        authorizReqCode}, this.onEndGetAuthCodeDelegate, this.onGetAuthCodeCompletedDelegate, userState);
        }
    }
}
